### ISSUE TITLE
linear_test.ipynb assumes wrong return type for seq_ekf and seq_ckf

### ISSUE THREAD

**Issue by murphyk** [EEA-sensors/parallel-non-linear-gaussian-smoothers#4]
The [ekf](https://github.com/EEA-sensors/parallel-non-linear-gaussian-smoothers/blob/master/parsmooth/sequential/extended.py#L92) funtction returns (ll, (mean, cov)), but the notebook 
writes
```
print(jnp.max(jnp.abs(par_ekf_filtered.mean - seq_ekf_filtered.mean)))
```
instead of
```
print(jnp.max(jnp.abs(par_ekf_filtered.mean - seq_ekf_filtered[1].mean)))
```
Ditto for seq_ckf.

**Comment by AdrienCorenflos** [comment]
Thanks, I fixed the other issues too.
